apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-nginx-proxy-chart.fullname" . }}
  labels:
    {{- include "s3-nginx-proxy-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "s3-nginx-proxy-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "s3-nginx-proxy-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3-nginx-proxy-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: s3-credentials
          secret:
            secretName: {{ include "s3-nginx-proxy-chart.fullname" . }}
        - name: proxy-config
          configMap:
            name: {{ include "s3-nginx-proxy-chart.fullname" . }}
        - name: nginx-httpd
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-cache
          emptyDir:
            medium: {{ .Values.cache.medium }}
            sizeLimit: {{ .Values.cache.sizeLimit }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-httpd
              mountPath: /etc/nginx/http.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
        - name: {{ .Chart.Name }}-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/srv/config.sh"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: s3-credentials
              mountPath: /etc/s3-credentials
            - name: proxy-config
              mountPath: /etc/proxy-config
            - name: nginx-httpd
              mountPath: /etc/nginx/http.d
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
